### ISSUE TITLE
Auth to Google Artifact Registry fails even when using `OauthAccessToken`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-gcp#258]
### Expected Behavior

Example flow:

```yaml
id: gcpArtifactRegistry
namespace: dev
tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        branch: main
        url: https://github.com/anna-geller/kestra-flows
      
      - id: fetchAuthToken
        type: io.kestra.plugin.gcp.auth.OauthAccessToken
        projectId: geller
        serviceAccount: "{{envs.gcp_creds}}"

      - id: pythonTask
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - python python-scripts/etl_script.py
        dockerOptions:
          image: europe-west3-docker.pkg.dev/geller/flows/python:latest
          dockerConfig: |
            {
              "auths": {
                "europe-west3-docker.pkg.dev": {
                    "username": "_json_keyfile",
                    "password": "{{outputs.fetchAuthToken.accessToken.tokenValue}}"
                    }
              },
              "credHelpers": {
                "europe-west3-docker.pkg.dev": "gcloud"
              }
            }
        runner: DOCKER
```

### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/3293067e-6e72-4509-9166-73eec15314fb)

Without running one of these commands (either gcloud auth or docker login) before, it doesn't seem to work:

```bash
gcloud auth configure-docker europe-west3-docker.pkg.dev
cat mykey.json | docker login -u _json_key --password-stdin https://europe-west3-docker.pkg.dev
```

It might be required to either:
1. add the gcloud CLI plugin https://github.com/orgs/kestra-io/projects/3/views/1?filterQuery=gcloud&pane=issue&itemId=27437640
2. add the Docker plugin https://github.com/orgs/kestra-io/projects/3/views/1?pane=issue&itemId=30479463 

To support it?

### Environment Information

- Kestra Version: develop-full docker 0.10.0

**Comment by anna-geller** [comment]
The version with oauth2accesstoken as username works, but the one with the JSON key didn't work for me (I tried various ways to parse it)

looks like for now, the best way might be to document the token option?

**Comment by anna-geller** [comment]
> You could also use base64 encoded service account with `"username": "_json_keyfile_base64"` this would avoid the need to manipulate JSON which can be tricky.

can you provide a full flow example @loicmathieu? do you mean this?

```yaml
id: gcpArtifactRegistry
namespace: dev
tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        branch: main
        url: https://github.com/anna-geller/kestra-flows
      
      - id: fetchAuthToken
        type: io.kestra.plugin.gcp.auth.OauthAccessToken
        projectId: geller
        serviceAccount: "{{envs.gcp_creds}}"

      - id: pythonTask
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - python python-scripts/etl_script.py
        dockerOptions:
          image: europe-west3-docker.pkg.dev/geller/flows/python:latest
          dockerConfig: |
            {
              "auths": {
                "europe-west3-docker.pkg.dev": {
                    "username": "_json_keyfile_base64",
                    "password": "{{outputs.fetchAuthToken.accessToken.tokenValue}}"
                    }
              },
              "credHelpers": {
                "europe-west3-docker.pkg.dev": "gcloud"
              }
            }
        runner: DOCKER
```

**Comment by loicmathieu** [comment]
No, you encore in base64 the SA and you pass it directly, it avoids dealing with JSON.
Something like this where the env variable KESTRA_GCP_CREDS is a a based64 encoding of your SA:

```yaml
id: gcpArtifactRegistry
namespace: dev
tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        branch: main
        url: https://github.com/anna-geller/kestra-flows

      - id: pythonTask
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - python python-scripts/etl_script.py
        dockerOptions:
          image: europe-west3-docker.pkg.dev/geller/flows/python:latest
          dockerConfig: |
            {
              "auths": {
                "europe-west3-docker.pkg.dev": {
                    "username": "_json_keyfile_base64",
                    "password": "{{envs.gcp_creds}}"
                    }
              }
            }
        runner: DOCKER
```

By the way, credHelpers can only works if the helper is installed and configured so it is for using local gcloud configuration and is not designed to be used for such use case.
