### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-gcp#265]
### Feature description

Currently in order to retrieve secrets hosted on GCP, we need to perform command : 

`gcloud secrets versions access "latest" --secret "MY_SECRET"` using the CLI.

Current flow looks like this :
```YAML
id: retrieve-gcloud-secret
namespace: dev
tasks:
  - id: get-credentials
    type: "io.kestra.plugin.gcp.cli.GCloudCLI"
    serviceAccount: "{{ globals['my-sa-json'] }}"
    commands:
      - gcloud secrets versions access "latest" --secret "MY_SECRETS_ON_GCP" --format json | tr -d '\n ' | xargs -0 -I {} echo '::{"outputs":{"gcloud":{}}}::'
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "Your secret value : {{ outputs['get-credentials'].vars['gcloud']['payload']['data'] }}"
```

Aside that the secret value is displayed in the logs, could be interesting to access them more easily

I am willing to do a PR 👍
