### ISSUE TITLE
PubSub trigger doesn't fire

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-gcp#268]
### Issue description

Reproducer flow:

```yaml
id: gcpPubSub
namespace: dev

tasks:
  - id: payload_log
    type: io.kestra.core.tasks.log.Log
    message: "{{ triggers.objects }}"

triggers:
  - id: get_payload
    type: io.kestra.plugin.gcp.pubsub.Trigger
    topic: kestra
    subscription: kestra-sub
    projectId: geller
    interval: PT1S
    maxRecords: 1
    serviceAccount: "{{ secret('GCP_CREDS') }}"
    autoCreateSubscription: false
```

Using a default setup, I created a topic "kestra" and a default subscription. Then I sent 2 messages from GCP console, yet no execution was triggered.

**Comment by tchiotludo** [comment]
Do you have any logs on the logs tabs for the flow?

**Comment by anna-geller** [comment]
the flow never gets triggered, it looks like the trigger either doesn't properly receive PubSub messages or it doesn't trigger flows correctly -- you can reproduce the flow directly to see it

**Comment by loicmathieu** [comment]
Just tested it and it works on my side.
The flow is triggered however the name of the variable is not the good one.

I use this flow:
```
id: gcpPubSub
namespace: dev

tasks:
  - id: payload_log
    type: io.kestra.core.tasks.log.Log
    message: "{{ trigger.uri }}"

triggers:
  - id: get_payload
    type: io.kestra.plugin.gcp.pubsub.Trigger
    projectId: my-project-id2
    topic: kestra
    subscription: kestra-sub
    interval: PT1S
    maxRecords: 1
    autoCreateSubscription: false
```
And have it trigger with `gcloud pubsub topics publish projects/methodical-mesh-238712/topics/kestra --message "Hello World"`.
