### ISSUE TITLE
Output ION file generated by PubSub Consume task is malformed and cannot be previewed

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-gcp#351]
Preview on the downloaded results from `PubSub` Consume task failed to be previewed. It gives Error 500.
![Screenshot 2024-03-23 at 3 57 46 PM](https://github.com/kestra-io/plugin-gcp/assets/6594483/219f6fc9-cd0e-41ac-8bef-83a9f92e0c0d)

However, it is able to read the uri using Render Expression.
![Screenshot 2024-03-23 at 4 08 41 PM](https://github.com/kestra-io/plugin-gcp/assets/6594483/b7594f75-92cf-433e-9503-e150201c8e6b)

### Steps To Reproduce

1. Use the example Publish task to publish the messages.
2. Then run the Consume task to consume these messages.
3. Preview the output of the Consume task.

### Environment Information

- Kestra Version: 0.15.5
- Plugin version: 0.15.5
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

Publish Task:
```yaml
id: "publish"
type: "io.kestra.plugin.gcp.pubsub.Publish"
projectId: <project-id>
serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
topic: topic-test
from:
-  data: "{{ 'base64-encoded-string-1' | base64encode }}"
   attributes:
       testAttribute: KestraTest
   messageId: '1234'
-  data: "{{ 'base64-encoded-string-2' | base64encode }}"
-  attributes:
       testAttribute: KestraTest
```

Consume Task
```yaml
id: pubsub-consume
namespace: dev
tasks:
  - id: "consume"
    type: "io.kestra.plugin.gcp.pubsub.Consume"
    projectId: <project-id>
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
    topic: smantri-test
    maxRecords: 3
    subscription: <subscription-id>
```

**Comment by Malaydewangan09** [comment]
@anna-geller, couldn't reproduce this on develop

Reproducer below
```yaml
id: cod_899076
namespace: malay-test

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello Kestra!

  - id: publish
    type: io.kestra.plugin.gcp.pubsub.Publish
    version: 0.23.0
    projectId: <project-id>
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
    topic: topic-test
    
    from:
    - data: "{{ 'base64-encoded-string-1' | base64encode }}"
      attributes:
          testAttribute: KestraTest
      messageId: '1234'
    - data: "{{ 'base64-encoded-string-2' | base64encode }}"
    - attributes:
          testAttribute: KestraTest

  - id: consume
    type: io.kestra.plugin.gcp.pubsub.Consume
    projectId: <project-id>
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
    topic: topic-test
    subscription: test-subscription
    maxRecords: 3

```
