### ISSUE TITLE
`io.kestra.plugin.gcp.pubsub.Consume` example throws `NullPointerException`

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-gcp#412]
### Expected Behavior

Trying to use the example on https://kestra.io/plugins/plugin-gcp/tasks/pubsub/io.kestra.plugin.gcp.pubsub.consume to consume messages from a Google PubSub topic.

### Actual Behaviour

With the topic, serviceAccount and projectId set, it still throws a NullPointerException with no clear indication on what the error is/

### Steps To Reproduce

```yaml
id: consume_pubsub
namespace: company.team

tasks:
  - id: "consume"
    type: "io.kestra.plugin.gcp.pubsub.Consume"
    topic: test-topic
    projectId: "snappy-nomad-422714-t8"
    maxRecords: 10
    serviceAccount: "{{ secret('GOOGLE_SA') }}"
```

### Environment Information

- Kestra Version: 0.17.8
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
