### ISSUE TITLE
`bigquery.Copy` not working with validation error

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-gcp#428]
### Actual Behaviour

This cannot be save due to this error:

> Internal server error: HV000030: No validator could be found for constraint ‘io.kestra.plugin.gcp.bigquery.StoreFetchDestinationValidation’ validating type ‘io.kestra.plugin.gcp.bigquery.Copy’. Check configuration for ‘tasks[0]’

```yaml
id: test_bq_copy
namespace: kestra.sandbox

tasks:
  - id: snapshot_table
    type: io.kestra.plugin.gcp.bigquery.Copy
    destinationTable: kestra-dev.bpimpaud.new_data_test
    operationType: COPY
    sourceTables:
      - kestra-dev.bpimpaud.data_from_db
    projectId: kestra-dev
    serviceAccount: "{{ secret('GCP_CREDS') }}"
```

The flow is fairly basic and use the example from plugin documentation

### Environment Information

- Kestra Version: 0.18.0
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): docker
- Java Version (If not docker):
