### ISSUE TITLE
No property 'fetch' exists in plugin 'io.kestra.plugin.gcp.bigquery.Query' 

### ISSUE THREAD

**Issue by GideonStowell** [kestra-io/plugin-gcp#474]
### Describe the issue

Using the `io.kestra.plugin.gcp.bigquery.Query` plugin and the attribute `fetch` will cause your flow to be marked as invalid and you'll be unable to save or upload it. 

Example Flow:

```
id: update-orders
namespace: bq
tasks:
  - id: update-orders
    type: io.kestra.plugin.gcp.bigquery.Query
    disabled: false
    sql: "{{ read('sql/update-orders.sql') }}"

pluginDefaults: 
  - type: io.kestra.plugin.gcp.bigquery.Query
    values:
      fetch: false # This line will be highlighted as invalid when you try to save
      priority: BATCH
      projectId: "{{inputs.BQ_PROJECT_ID}}"
      serviceAccount: "{{ json(outputs.collect_secrets.outputs.secrets).GCP_TOKEN }}"
```

Error message:
```
pluginDefaults[0]: Invalid Plugin Default: No property 'fetch' exists in plugin 'io.kestra.plugin.gcp.bigquery.Query' 
```

According to the documentation [here](https://kestra.io/plugins/plugin-gcp/tasks/bigquery/io.kestra.plugin.gcp.bigquery.query#fetch), `fetch` is a valid attribute to use.

### Environment

- Kestra Version: v0.20.7
- Kestra Runtime: Docker
