### ISSUE TITLE
ExtractToGcs dones't work "No value present"

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-gcp#485]
### Describe the issue

```yaml
id: myflow
namespace: dev.ben

tasks:
  - id: extract_btc_transactions_to_gcs
    type: io.kestra.plugin.gcp.bigquery.ExtractToGcs
    destinationUris:
      - "gs://bpimpaud/*.csv"
    sourceTable: "kestra-sandbox.shiny_rocks.marketing_investments"
    printHeader: true
    projectId: kestra-sandbox
    format: CSV
    serviceAccount: |
      REDACTED
```

![image](https://github.com/user-attachments/assets/7a98f29d-1375-46fb-956a-85f15e8291a9)

### Environment

- Kestra Version: develop
