### ISSUE TITLE
GCS Upload task generates directories in `from` property in GCS, despite different path specified in `to` field

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-gcp#488]
### Describe the issue

This user from DTC is trying to generate CSV files with Python and then upload them all to GCS. 

However this task doesn't work as expected.

```yaml
- id: upload_to_gcs
  type: io.kestra.plugin.gcp.gcs.Upload
  from: "{{ outputs.python.outputFiles[taskrun.value] }}"
  to: "{{ render(vars.gcs_file) }}/{{ taskrun.value }}"
```

`{{ outputs.python.outputFiles[taskrun.value] }}` renders as `kestra:///bigbrotherbrasil/bbb-gcp-setup-nominations/executions/5QEwGUprX6v22l6iUpFe19/tasks/python/1dABIPZPVDENVVsD5wFPre/7LlQUumzl4rmzuh2iSZtCX-Eviction_results_1.csv` which is how it is stored in Kestra but also the path to the file is added to GCS,

`{{ render(vars.gcs_file) }}/{{ taskrun.value }}` renders as `gs://will-kestra-python-example/Eviction_results_1.csv` which is how the file appears in GCS in the correct location

When this is run, you get the file in the correct location to the `to` field, but also all the folders to match the `from` field.

![Image](https://github.com/user-attachments/assets/8498b5b3-1913-4b37-adc5-53c1ee730048)

Full example from student, I have a demo set up working if you want me to test.

```yaml
id: bbb_gcp_setup_nominations
namespace: bigbrotherbrasil
variables:
  gcs_file: "gs://{{kv('BBB_GCP_BUCKET_NAME')}}"
  table: "{{kv('BBB_GCP_DATASET')}}"
  data: "{{outputs.python.outputFiles}}"
tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/andrea-leonel/BigBrotherBrasil_Kestra
      - id: python
        type: io.kestra.plugin.scripts.python.Commands
        namespaceFiles:
          enabled: true
        beforeCommands:
          - pip install pandas requests beautifulsoup4 ipython Unidecode lxml html5lib
        commands:
          - python BBB_Nominations_scrape.py
        outputFiles:
          - "Nominations_*.csv"
          - "Individual_nominations_*.csv"
          - "Eviction_results_*.csv"
  
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 1
    values: "{{ outputs.python.outputFiles | jq('keys[]') }}"    
    tasks:
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: "{{ outputs.python.outputFiles[taskrun.value] }}"
      
      - id: upload_to_gcs
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{ outputs.python.outputFiles[taskrun.value] }}"
        to: "{{ render(vars.gcs_file) }}/{{ taskrun.value }}"

      - id: upload_to_bq
        type: io.kestra.plugin.gcp.bigquery.Query
        sql:
           CREATE OR REPLACE EXTERNAL TABLE `{{kv('BBB_GCP_PROJECT_ID')}}.{{render(vars.table)}}.{{taskrun.value}}`
           OPTIONS (
            format = 'CSV',
            uris = ['{{render(vars.gcs_file)}}/{{taskrun.value}}'],
            ignore_unknown_values = TRUE
          );

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('BBB_GCP_CREDS')}}"
      projectId: "{{kv('BBB_GCP_PROJECT_ID')}}"
      location: "{{kv('BBB_GCP_LOCATION')}}"
      bucket: "{{kv('BBB_GCP_BUCKET_NAME')}}"
```

### Environment

- Kestra Version: develop
